import React from 'react';
import Link from 'next/link';
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from '@/components/ui/card';
import { Tabs, TabsContent, TabsList, TabsTrigger } from '@/components/ui/tabs';
import { Badge } from '@/components/ui/badge';
import { Table, TableBody, TableCell, TableHead, TableHeader, TableRow } from '@/components/ui/table';
import { ArrowLeft, Info } from 'lucide-react';
import {
  Tooltip,
  TooltipContent,
  TooltipProvider,
  TooltipTrigger,
} from '@/components/ui/tooltip';

export const metadata = {
  title: 'DeFi Sector | CanHav',
  description: 'Explore DeFi protocols, metrics, and performance indicators',
};

// Sample data for DeFi protocols
const defiProtocols = [
  {
    name: 'Uniswap',
    category: 'DEX',
    tvl: '$5.2B',
    volume24h: '$1.2B',
    fees24h: '$3.6M',
    revenue: '$1.2M',
    psRatio: '32.5',
  },
  {
    name: 'Aave',
    category: 'Lending',
    tvl: '$4.8B',
    volume24h: '$320M',
    fees24h: '$960K',
    revenue: '$192K',
    psRatio: '41.2',
  },
  {
    name: 'Curve',
    category: 'DEX',
    tvl: '$3.7B',
    volume24h: '$450M',
    fees24h: '$1.35M',
    revenue: '$270K',
    psRatio: '28.6',
  },
  {
    name: 'MakerDAO',
    category: 'Lending',
    tvl: '$7.1B',
    volume24h: '$210M',
    fees24h: '$630K',
    revenue: '$630K',
    psRatio: '15.3',
  },
  {
    name: 'Compound',
    category: 'Lending',
    tvl: '$2.9B',
    volume24h: '$180M',
    fees24h: '$540K',
    revenue: '$108K',
    psRatio: '36.8',
  },
];

// Metrics definitions
const metrics = [
  {
    name: 'TVL (Total Value Locked)',
    description: 'The total value of cryptocurrency assets deposited in a DeFi protocol. It represents the size and liquidity of the protocol.',
    importance: 'High TVL indicates strong user trust and protocol adoption. However, it should be evaluated alongside other metrics as it can be artificially inflated.',
    calculation: 'Sum of all assets deposited in the protocol, converted to USD value.',
  },
  {
    name: 'Volume',
    description: 'The total amount of assets traded or processed through a protocol over a specific time period.',
    importance: 'High volume suggests active usage and liquidity. Consistent volume growth indicates increasing adoption.',
    calculation: 'Sum of all transaction values processed through the protocol in a given time period.',
  },
  {
    name: 'Fees',
    description: 'The total fees generated by a protocol from user transactions.',
    importance: 'Fees represent the protocol\'s ability to monetize its services and are a key indicator of economic sustainability.',
    calculation: 'Sum of all fees charged on transactions. Typically a percentage of transaction volume.',
  },
  {
    name: 'Revenue',
    description: 'The portion of fees that goes to the protocol treasury or token holders after paying liquidity providers and other expenses.',
    importance: 'Revenue is a critical metric for valuing a protocol as a business and assessing its long-term viability.',
    calculation: 'Total fees minus payments to liquidity providers and other operational costs.',
  },
  {
    name: 'P/S Ratio (Price-to-Sales)',
    description: 'A valuation metric that compares a protocol\'s fully diluted market cap to its annualized revenue.',
    importance: 'Lower P/S ratios may indicate undervalued protocols, while very high ratios might suggest overvaluation.',
    calculation: 'Fully Diluted Market Cap ÷ (Annual Revenue). For protocols, annual revenue is often estimated by multiplying recent daily/weekly revenue by 365/52.',
  },
];

export default function DefiSectorPage() {
  return (
    <div className="container py-10">
      <Link href="/sectors" className="flex items-center text-sm text-muted-foreground hover:text-foreground mb-6">
        <ArrowLeft className="mr-2 h-4 w-4" />
        Back to all sectors
      </Link>

      <div className="mb-8">
        <h1 className="text-4xl font-bold mb-2">DeFi Sector</h1>
        <p className="text-lg text-muted-foreground">
          Decentralized Finance (DeFi) protocols that enable lending, trading, and yield generation without intermediaries
        </p>
      </div>

      <Tabs defaultValue="overview" className="w-full">
        <TabsList className="grid w-full grid-cols-3 mb-8">
          <TabsTrigger value="overview">Overview</TabsTrigger>
          <TabsTrigger value="metrics">Metrics Explained</TabsTrigger>
          <TabsTrigger value="protocols">Top Protocols</TabsTrigger>
        </TabsList>

        <TabsContent value="overview" className="space-y-6">
          <Card>
            <CardHeader>
              <CardTitle>What is DeFi?</CardTitle>
              <CardDescription>Decentralized Finance explained</CardDescription>
            </CardHeader>
            <CardContent className="space-y-4">
              <p>
                Decentralized Finance (DeFi) refers to financial services and applications built on blockchain technology that operate without centralized intermediaries like banks or financial institutions. Instead, DeFi uses smart contracts to enable peer-to-peer financial services.
              </p>
              <p>
                DeFi applications span various categories including decentralized exchanges (DEXs), lending platforms, yield aggregators, derivatives, insurance, and asset management tools. These protocols allow users to trade, borrow, lend, and earn yield on their crypto assets in a permissionless and transparent manner.
              </p>
              <p>
                The DeFi sector emerged primarily on Ethereum but has expanded to multiple blockchains including Solana, Avalanche, and others. DeFi innovation continues at a rapid pace, with new protocols and financial primitives constantly being developed and tested.
              </p>

              <div className="mt-6">
                <h3 className="text-lg font-medium mb-3">Key DeFi Categories</h3>
                <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-4">
                  <Card>
                    <CardHeader className="pb-2">
                      <CardTitle className="text-base">Decentralized Exchanges (DEXs)</CardTitle>
                    </CardHeader>
                    <CardContent className="text-sm">
                      Platforms that enable peer-to-peer trading of cryptocurrencies without a central authority. Examples: Uniswap, Curve, dYdX.
                    </CardContent>
                  </Card>
                  <Card>
                    <CardHeader className="pb-2">
                      <CardTitle className="text-base">Lending Protocols</CardTitle>
                    </CardHeader>
                    <CardContent className="text-sm">
                      Platforms where users can lend their assets to earn interest or borrow assets by providing collateral. Examples: Aave, Compound, MakerDAO.
                    </CardContent>
                  </Card>
                  <Card>
                    <CardHeader className="pb-2">
                      <CardTitle className="text-base">Yield Aggregators</CardTitle>
                    </CardHeader>
                    <CardContent className="text-sm">
                      Services that automatically move user funds between different protocols to maximize yield. Examples: Yearn Finance, Beefy Finance.
                    </CardContent>
                  </Card>
                </div>
              </div>
            </CardContent>
          </Card>
        </TabsContent>

        <TabsContent value="metrics" className="space-y-6">
          <Card>
            <CardHeader>
              <CardTitle>DeFi Metrics Explained</CardTitle>
              <CardDescription>Understanding key performance indicators for DeFi protocols</CardDescription>
            </CardHeader>
            <CardContent>
              <div className="space-y-6">
                {metrics.map((metric, index) => (
                  <div key={index} className="p-4 border rounded-lg">
                    <h3 className="text-lg font-medium flex items-center">
                      {metric.name}
                      <TooltipProvider>
                        <Tooltip>
                          <TooltipTrigger asChild>
                            <Info className="h-4 w-4 ml-2 text-muted-foreground" />
                          </TooltipTrigger>
                          <TooltipContent className="max-w-sm">
                            <p>{metric.calculation}</p>
                          </TooltipContent>
                        </Tooltip>
                      </TooltipProvider>
                    </h3>
                    <p className="mt-2 text-muted-foreground">{metric.description}</p>
                    <div className="mt-3 pt-3 border-t">
                      <h4 className="text-sm font-medium mb-1">Why it matters:</h4>
                      <p className="text-sm">{metric.importance}</p>
                    </div>
                  </div>
                ))}
              </div>
            </CardContent>
          </Card>
        </TabsContent>

        <TabsContent value="protocols">
          <Card>
            <CardHeader>
              <CardTitle>Top DeFi Protocols</CardTitle>
              <CardDescription>Key metrics for leading DeFi protocols</CardDescription>
            </CardHeader>
            <CardContent>
              <div className="overflow-x-auto">
                <Table>
                  <TableHeader>
                    <TableRow>
                      <TableHead>Protocol</TableHead>
                      <TableHead>Category</TableHead>
                      <TableHead>TVL</TableHead>
                      <TableHead>24h Volume</TableHead>
                      <TableHead>24h Fees</TableHead>
                      <TableHead>Revenue</TableHead>
                      <TableHead>P/S Ratio</TableHead>
                    </TableRow>
                  </TableHeader>
                  <TableBody>
                    {defiProtocols.map((protocol) => (
                      <TableRow key={protocol.name}>
                        <TableCell className="font-medium">{protocol.name}</TableCell>
                        <TableCell>
                          <Badge variant="outline">{protocol.category}</Badge>
                        </TableCell>
                        <TableCell>{protocol.tvl}</TableCell>
                        <TableCell>{protocol.volume24h}</TableCell>
                        <TableCell>{protocol.fees24h}</TableCell>
                        <TableCell>{protocol.revenue}</TableCell>
                        <TableCell>{protocol.psRatio}</TableCell>
                      </TableRow>
                    ))}
                  </TableBody>
                </Table>
              </div>
              <p className="text-xs text-muted-foreground mt-4">
                Data is for illustrative purposes and may not reflect current market conditions. Last updated: July 7, 2025.
              </p>
            </CardContent>
          </Card>
        </TabsContent>
      </Tabs>
    </div>
  );
}
